export const ADD_ARTICLE = "ADD_ARTICLE";
export const DATA_LOADED = "DATA_LOADED";

export const ADD_ARTICLE_REQ = "ADD_ARTICLE_REQ";
export const API_ERRORED = "API_ERRORED";
export const DATA_REQUESTED = "DATA_REQUESTED";
export const FOUND_BAD_WORD = "FOUND_BAD_WORD";
export const FOUND_BLANK_WORD = "FOUND_BLANK_WORD";